### ISSUE TITLE
Can't fetch containers on F32 / gnome-shell 3.36

### ISSUE THREAD

**Issue by mrguitar** [rgolangh/gnome-shell-extension-containers#10]
Thanks for the great extension. Clicking the podman icon with F32 beta on the tray says "Error occurred when fetching containers"

This is what I see in the journal:
Mar 25 08:18:39 hostname.local gnome-shell[2046]: found 4 containers
Mar 25 08:18:39 hostname.local gnome-shell[2046]: Error occurred when fetching containers: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?

I'm not sure how helpful this is or what other info is needed, but it looks like something changed in 3.36.

**Comment by rgolangh** [comment]
@mrguitar fixed on 3.36.1 branch and merged to master. I'll post it to the gnome extension page as well.
BTW how did you install the extension?

**Comment by mrguitar** [comment]
Awesome thanks for the fix! I installed this from the gnome extensions web site. It just prompted me to update it which was really nice too. Thanks again!
