### ISSUE TITLE
icon that can be improved

### ISSUE THREAD

**Issue by xzj8b3** [rgolangh/gnome-shell-extension-containers#12]
change icons smaller without contour and suitable for dark themes ...ugly

**Comment by rgolangh** [comment]
@xzj8b3 can you help here?

**Comment by xzj8b3** [comment]
> @xzj8b3 can you help here? Sketch something, point me to an example.

Uninstalled, it seems to give bad slowdowns to the animation at startup and not only ... in the future I will review it again!
