### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by idnovic** [rgolangh/gnome-shell-extension-containers#2]
Fedora 30
I installed the extension and in the menu I can just see `Error occurred when fetching containers`
I looked at the source code and found 1 error:

```
#$podman ps -a --format '{{json .}}'
Error: template: data:1: function "json" not defined
```

but `podman ps -a --format '{{.}}'` works

Still the extension does not work before and after I made the change. I would appreciate it, when you would fix the extension.

**Comment by rgolangh** [comment]
This was reported [here](https://github.com/containers/libpod/issues/2671) under podman and looks like this should be back working with latest podman version. But to be safe I'll just fix it to work with {{.}} like you mentioned - thanks!

**Comment by rgolangh** [comment]
Fixes under the branch https://github.com/rgolangh/gnome-shell-extension-containers/tree/fedora-30

Extension uploaded for review and will be available in few days if everything goes well.

**Comment by idnovic** [comment]
Thank you. Seems to work now. Still need to test it for the functionality :)

**Comment by rgolangh** [comment]
Awesome, thanks for using and reporting the issue. 

BTW I'd love to get more suggestions for any enhancements or changes, feel free to open more issues.

**Comment by idnovic** [comment]
So I tried to record it, following problem (you can see it in the gif just the top bar is missing)
The menu moves to the left because screen space is missing on the right side. The gif is at the top most right corner. Just a few pixel missing for the top bar. 

What happens is that after I close a menu the extension moves left. But the icon in the top bar stays at the position of the first frame in the gif.
![Peek 2019-07-01 09-19](https://user-images.githubusercontent.com/28260793/60417888-d1b8b200-9be1-11e9-834a-f082a3290678.gif)

**Comment by rgolangh** [comment]
Fixed, can you check the latest fedora-30 branch?

**Comment by idnovic** [comment]
yes awesome. Much better :)
