### ISSUE TITLE
Container submenu is not expanded

### ISSUE THREAD

**Issue by rmarting** [rgolangh/gnome-shell-extension-containers#23]
Container submenu is not expanded unless you click inside of the white arrow on the right, so it is very difficult for the user to navigate across the different containers. It is very complicated to click in the right place of the menu to expand the menu, however when the menu is expanded you could click in any place of each opcion.

Is it something wrong in my envionrment? Fedora 33 with GNome.

**Comment by rgolangh** [comment]
I can't reproduce this behaviour on latest Gnome (40) with Fedora 34 with the latetst publish extension version.
What version of the extension are you using?

**Comment by rmarting** [comment]
My setup is Gnome 3.38.5 using X11 with Fedora 33. I have no plan in short to upgrade to Fedora 34.

**Comment by rmarting** [comment]
@rgolangh After upgrading to Fedora 34 and Gnome 40.1.0 everything worked successfully. It seems that in previous version of Gnome is not working fine. IMHO, we could close the issue.
Thanks!

**Comment by rgolangh** [comment]
Thank you so much for that feedback, this helps a lot.
I hope this will stay usable as gnome 40 progresses!
