### ISSUE TITLE
let me copy information

### ISSUE THREAD

**Issue by idnovic** [rgolangh/gnome-shell-extension-containers#3]
The extension displays information and currently only 2 of the displayed are also with a feature after click.

If any of the other informations displayed do not have a feature behind the text just copy the displayed information to the clipboard after click.

So I can use the information in any other fashion.
Hope that makes sense.

**Comment by idnovic** [comment]
I am not sure but I think it does not work on wayland.

**Comment by rgolangh** [comment]
The paste support doesn't work?

I have it working on gnome-shell 3.32.2 Fedora 30

**Comment by idnovic** [comment]
I meant that I can not copy information from the extension.
Which items can I expect to copy to clipboard on click?

Are the informations only copied for running containers?

**Comment by idnovic** [comment]
I figured it out
My gnome shell on wayland is buggy. Probably because I cherry picked commits.
With an clipboard indicator extension I can see the content. So the shell looses it somehow.
