### ISSUE TITLE
Add support for managing pods via systemd

### ISSUE THREAD

**Issue by masayag** [rgolangh/gnome-shell-extension-containers#30]
With podman's [integration with systemd](https://www.redhat.com/sysadmin/improved-systemd-podman), pods can be managed via unit files.
Hence, start/stop/restart will be controlled via the service files instead by interacting with podman directly.

**Comment by masayag** [comment]
Podman is capable to generate systemd files for the pod.
Similar to what flotta is doing, it relies on podman to generate systemd service for a pod, but it invokes the pod by controlling the service.
Not sure if the extension should store any matching between the pod to its systemd service.
If this isn't a functionally that is expected to be provided by the extension, it can be closed.

**Comment by rgolangh** [comment]
I'm running over the pods inspect output and I don't have a piece of the data to determine it was started by systemd.
Maybe this worth a label of `podman/managed-by="systemd"` added by the `podman generate systemd.
With a label I can at least set some visual cue on the container name, that it is managed by systemd (hence careful)

I'm leaving this discussion open for now

**Comment by rgolangh** [comment]
My bad, there's a label `PODMAN_SYSTEM_UNIT`
