### ISSUE TITLE
Allow to generate podman command

### ISSUE THREAD

**Issue by masayag** [rgolangh/gnome-shell-extension-containers#34]
In certain cases, it is useful to have the exact podman command that starts the pod/container.
In a similar manner of "copy login command" of OCP web console that allows the user to run it from the CLI.

**Comment by rgolangh** [comment]
I can see that today podman already implemented something to help with that:
`podman inspect  X  -f '{{ .Config.CreateCommand }}' `

So either I add that as a new action, or create a general 'Copy Container Details' action that will copy all the inspect details to clipboard. Either way its a nice addition.
Adding 'Copy Systemd Unit' or 'Copy Pod Spec' sounds like 2 useful addition as well
