### ISSUE TITLE
Add support to GNOME 42

### ISSUE THREAD

**Issue by baco** [rgolangh/gnome-shell-extension-containers#36]
GNOME 42 has been out for a while, [gnome-shell-extension-containers](https://github.com/rgolangh/gnome-shell-extension-containers) needs to support it

**Comment by rgolangh** [comment]
#31 handles that among other changes.
The updates is under review on extensions.gnome.org and hopefully be available soon

**Comment by rgolangh** [comment]
@baco  @melvinotieno is this working for you now?

**Comment by melvinotieno** [comment]
Yes @rgolangh , thank you
