### ISSUE TITLE
start / stop buttons doesn't change after clicked

### ISSUE THREAD

**Issue by sombriks** [rgolangh/gnome-shell-extension-containers#39]
i am running fedora 35 and i only see the change on start/stop behavior when i open the menu again.

is it possible to close menu after i click on it or make the change on the fly?

**Comment by rgolangh** [comment]
Making the active presented pod refreshable is plausible, but I don't know when will I get to fix this.

**Comment by sombriks** [comment]
> Making the active presented pod refreshable is plausible, but I don't know when will I get to fix this.

i did a quick hack on the pull request mentioned on this issue, it could be good enough for now.
