### ISSUE TITLE
do not close extension after click on start/stop/pause...

### ISSUE THREAD

**Issue by idnovic** [rgolangh/gnome-shell-extension-containers#4]
If possible do not close extension after I clicked on start/stop/pause...
Only close extension after I clicked on rm

Later versions of the extension may offer more feedback and I thing it would be helpful to be able to see any new information provided after I clicked a feature button

**Comment by rgolangh** [comment]
If I implement that it means I would have to refresh the menu item as well. Otherwise it will just enable unsupported actions on the container. I'd have to figure out how to do that and what's the trade off.
