### ISSUE TITLE
Bug: Gnome 43 theme interference with "Quick Settings" menu button colors

### ISSUE THREAD

**Issue by rupert160** [rgolangh/gnome-shell-extension-containers#42]
when the extension is active it seems to clobber the button theme in the new Quick Settings menu like so:
![image](https://user-images.githubusercontent.com/5459901/198873560-2ed0cc8a-95ce-4b94-a6b9-1589f266916f.png)
When it should actually look like so:
![image](https://user-images.githubusercontent.com/5459901/198873582-5cad3f97-5dda-4354-81de-9fc0ec686f35.png)

**Comment by rgolangh** [comment]
Confirmed on Fedora 38 as well.

Will be glad for help here
