### ISSUE TITLE
Log window closes immediately when container stops working

### ISSUE THREAD

**Issue by Semo** [rgolangh/gnome-shell-extension-containers#44]
Hey there! I would like to ask you, if it was possible to solve an issue with the log display on Ubuntu 20.04 LTS . It runs fine, if the container runs, but closes immediately, if the container stopped. 
This is a problem, if I want to find out, what error was thrown. Then I have to open the terminal and go the usual way via podman container log....

Could you leave the log open until the user kills the window?

Best regards and thank you for your work!
Sebastian

**Comment by rgolangh** [comment]
Thanks for reporting this. I'm going to perform the internal command with bash and just wait for any key input after that. It should keep it open till you hit any key.
