### ISSUE TITLE
alternative icon color

### ISSUE THREAD

**Issue by idnovic** [rgolangh/gnome-shell-extension-containers#5]
In my top bar are only black/white or greyish icons.
I edited the original icon to fit more into my system.
Attached below in case you want to provide alternative icons one day.

![podman-icon](https://user-images.githubusercontent.com/28260793/60509303-e7ef6c80-9ccc-11e9-8e19-4e93968a3a03.png)

**Comment by rgolangh** [comment]
Thanks for the icon work @idnovic , it is now merged to master commit c85636c1fbded9fbc212d09213121aa6cc4c2504
