### ISSUE TITLE
Enable not working on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by Semo** [rgolangh/gnome-shell-extension-containers#51]
I just pulled your changes. Beforehand `git`  annoyed me with some merge problems (I didn't touch the repo at all since first pull) like `git pull origin main `. Then I wanted to build it as written in the README. 

Unfortunately it won't enable, if the message is correct.  Please see enclosed terminal output:
```
sudo make all              
gnome-extensions pack -f --extra-source=podman-icon.png --extra-source=classic.css --extra-source=modules
gnome-extensions install -f containers@royg.shell-extension.zip
gnome-extensions enable containers@royg
Fehler beim Verbinden zur GNOME-Shell  --> (Translates to: Error connecting to GNOME-Shell)
make: *** [Makefile:14: enable] Fehler 2     --> (Fehler=Error)
```

If I should provide further information, drop me a line how to and I'll try my very best.
Thank you very much. Cheers!

**Comment by rgolangh** [comment]
I installed ubuntu 22.04.2 LTS in a VM and I got a similar error, but from dbus. I restarted dbus.service (which rebooted the VM) and then the extension loaded. 
Maybe you can just logout/login and that would make it work. I think this is something the gnome-extension command should handle. If they won't anytime soon then maybe we should add something in the make file that will suggest a logout/login?
