### ISSUE TITLE
Please update for GNOME 45

### ISSUE THREAD

**Issue by skewty** [rgolangh/gnome-shell-extension-containers#52]
Please update for GNOME 45.

GNOME 45 does imports differently.
See: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by skewty** [comment]
I have most of the work done already in my fork at:
https://github.com/skewty/gnome-shell-extension-containers

The GUI still needs to work and the tray icon isn't working yet.

![image](https://github.com/rgolangh/gnome-shell-extension-containers/assets/9087223/479bf20f-9d6c-46d4-868c-b5a2b4baf146)

**Comment by rgolangh** [comment]
@skewty thanks a lot for that issue and bringing that esm change to my attention. 
Do you want to send a PR for those imports?

**Comment by rgolangh** [comment]
I merged your PR #53 , thanks a lot for that.
I also Fixed the ugly gray background on https://github.com/rgolangh/gnome-shell-extension-containers/commit/3533ce6482a1c1569537812604120109d29e0eea
