### ISSUE TITLE
Extension wont start on gnome-shell 44.7 after latest update

### ISSUE THREAD

**Issue by Dylancyclone** [rgolangh/gnome-shell-extension-containers#55]
After the latest update, which I believe was to add support for gnome 45 (https://github.com/rgolangh/gnome-shell-extension-containers/issues/52#issue-1921155552), I'm now getting a similar import error running gnome 44.7
![image](https://github.com/rgolangh/gnome-shell-extension-containers/assets/19830705/b6e053c7-f910-42df-93d7-3876cb075df6)
![image](https://github.com/rgolangh/gnome-shell-extension-containers/assets/19830705/86ca7ab3-7680-47f1-8402-26ea7f64a972)

Thank you for making this extension!

**Comment by rgolangh** [comment]
Totally my bad, thanks for reporting - working on it

**Comment by rgolangh** [comment]
All fixed are merged to the gnome-shell-44 branch and were tested on fedora 38. 
The extension version 30 under gnome shell version 44 should work for you. Can you confirm?

**Comment by Dylancyclone** [comment]
Everything appears to be working again! Thank you!
