### ISSUE TITLE
[Feature Request] There are options for Change targeted terminal

### ISSUE THREAD

**Issue by benyaminl** [rgolangh/gnome-shell-extension-containers#57]
Hello, I just want to ask, is it possible to change the 

https://github.com/rgolangh/gnome-shell-extension-containers/blob/0d76598003c269e1f7ff4fae387c351e59611ab2/src/modules/podman.js#L266-L268

With other terminal command? 

I'm on gnome but I'm not using gnome-terminal (sorry, haha...)

Or I need to change the code myself for that? 

Thank you 

EDIT: 

For now I do have workaround by making gnome-terminal shell script to get the command using xfce4-terminal 
/usr/local/bin/gnome-terminal
```bash
#!/bin/bash
if [ $1 == '--' ]; then
  shift
  xfce4-terminal -x $@
else
  xfce4-terminal $@
fi  
```

**Comment by rgolangh** [comment]
Thanks for reporting this.
:+1: +1 for clever script , but I would hate to force you do that. I think it should be easy to put that in a setting, and fallback to gnome terminal otherwise.

**Comment by rgolangh** [comment]
@benyaminl can you please checkout the branch from #58 and configure your terminal? I don't have an installation with xfce4 at the moment. I did test few other terminals, some run as flatpaks.

**Comment by benyaminl** [comment]
> @benyaminl can you please checkout the branch from #58 and configure your terminal? I don't have an installation with xfce4 at the moment. I did test few other terminals, some run as flatpaks.

Yeah, thanks man it works 

![image](https://github.com/user-attachments/assets/8bfe7fb1-20fd-4c07-8b08-dec9ffce04d6)

Just the process of running from the alpha/test version is quite strange I guess, I need to logout and relogin to make the new version works. 

the command line for xfce terminal is 

`xfce4-terminal -x `

**Comment by rgolangh** [comment]
what do you see in the journalctl  and what happens if you don't add the space? 
I tested here with a script, similar to what you did, and I don't see the space is needed.

**Comment by benyaminl** [comment]
@rgolangh sorry, seems it works as it's without space, I just retest it.
