### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by skewty** [rgolangh/gnome-shell-extension-containers#59]
Please add support for newest version of GNOME.

**Comment by rgolangh** [comment]
This is part of #58 and is merged and released to version 1.1.0
I'm pushing this to extensions.gnome.org for review now and once it is approved I'll close this.

**Comment by rgolangh** [comment]
The extension's version 1.1.0 is now available from https://extensions.gnome.org/extension/1500/containers/ to versions 45, 46, and 47 of gnome.
