### ISSUE TITLE
Bug: Error shown, when no container is present

### ISSUE THREAD

**Issue by daniel-wtd** [rgolangh/gnome-shell-extension-containers#7]
Hey,

when no container is present, the extension shows an error "Error occured when fetching container". A better suggestion would be "No container present".

Would be aweome to see this fixed. Thanks a lot for the cool extension.

**Comment by rgolangh** [comment]
Thanks for reporting this and finding is useful!

I'll close the issue  till the update is available at extensions.gnome.org. Meanwhile you can download it test it your self you can.
