### ISSUE TITLE
Bug: can't get menu to display under fedora 31 / gnome 3.34.1

### ISSUE THREAD

**Issue by jmbegley** [rgolangh/gnome-shell-extension-containers#8]
On a clean install of fedora 31, I can't get the menu to display at all. I only get the error message "Error occurred when fetching containers".

I have podman 1.6.2, libgpod 0.8.3, gnome shell 3.34.1 and the latest version of the containers extension from the extension.gnome.org website.

Looking in the log files, I see a lot of messages stating:

Usage of object.actor is deprecated for ContainersMenu
get@resource:///org/gnome/shell/ui/environment.js:242:29
renderMenu@/home/james/.local/share/gnome-shell/extensions/containers@royg/extension.js:80:9
_init/<@/home/james/.local/share/gnome-shell/extensions/containers@royg/extension.js:56:17
Error occurred when fetching containers
found 4 containers

**Comment by rgolangh** [comment]
Fixed on #8b045be including a performance improvement when opening the main extension menu.
